export const GET_TOP_RATED_MOVIES_PENDING = 'GET_TOP_RATED_MOVIES_PENDING';
export const GET_TOP_RATED_MOVIES_SUCCESS = 'GET_TOP_RATED_MOVIES_SUCCESS';
export const GET_TOP_RATED_MOVIES_ERROR = 'GET_TOP_RATED_MOVIES_ERROR';
export const GET_MOVIE_GENRES_PENDING = 'GET_MOVIE_GENRES_PENDING';
export const GET_MOVIE_GENRES_SUCCESS = 'GET_MOVIE_GENRES_SUCCESS';
export const GET_MOVIE_GENRES_ERROR = 'GET_MOVIE_GENRES_ERROR';
