export const GET_TOP_RATED_MOVIES_PENDING = 'GET_TOP_RATED_MOVIES_PENDING';
export const GET_TOP_RATED_MOVIES_SUCCESS = 'GET_TOP_RATED_MOVIES_SUCCESS';
export const GET_TOP_RATED_MOVIES_ERROR = 'GET_TOP_RATED_MOVIES_ERROR';
